"""added username

Revision ID: 0a9650280427
Revises: 8e0c7ac2982a
Create Date: 2023-07-14 14:51:25.963528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9650280427'
down_revision = '8e0c7ac2982a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['Username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Username')

    # ### end Alembic commands ###
